---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  chartRef:
    kind: OCIRepository
    name: cilium
  interval: 1h
  values:
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - 10.42.0.0/16
